#!/usr/bin/python

import os
import sys

sys.path.append(os.path.join(
    os.path.realpath(os.path.dirname(__file__)),
    "src"))

if __name__ == "__main__":
    sys.argv = sys.argv[1:]
    execfile(sys.argv[0])